# Generated by Django 5.0 on 2025-03-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile Phone'), ('laptop', 'Laptop'), ('smartwatch', 'Smart Watch'), ('buds', 'Buds')], max_length=20),
        ),
    ]
